name: Jon Slyman
favicon: null
layout_spectrum: 0.7675267574377358
typography_spectrum: 0.46908821212127805
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ADD7F6'
    - '#87BFFF'
    - '#3F8EFC'
    - '#2667FF'
    - '#3B28CC'
  brandStrength: 0.8262148241046816
  lightness: 0.5581848209258169
  saturation: 0.24449068633839488
  rhythmicContrast: 0.06159756681881845
purpose: []
